kaltura/playkit-js-dash

src/dash-adapter.js
test/src/dash-adapter.spec.js

Fix for
FEC-6968 - [Win10_Chrome][Player_V3] - Player is loading endlessly
THIS IS A TEMPORARY FIX AND SHOULD REVERTED when shaka will fix this:
https://github.com/google/shaka-player/issues/961
see also:
https://github.com/google/shaka-player/issues/880

fix(FEC-6968): loadstart issue

---

package.json
yarn.lock

set shaka version (2.2.0 instead of latest) in package.json

chore: set shaka version (2.2.0) in package.json

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Please add a detailed description of the change, weather it's an enhancement or a bugfix.

fix(FEC-7207): listen to shaka buffering event

---

.eslintrc.json
karma.conf.js
src/dash-adapter.js
webpack.config.js

add export of name and version of library.

feat: export name and version on module

---

src/dash-adapter.js
src/default-config.json

Add default-config.json for component.
Initial config - ignore VTT http bad response and parse issues - closes FEC-7593.

feat: add default-config json container

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

fix: build

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Please add a detailed description of the change, weather it's an enhancement or a bugfix.

chore: use EventType to get the playkit events

---

src/dash-adapter.js

Remove destroy from `DrmProtocol` interface since it has no meaning and we're overriding the old protocol with the new protocol on change media.

fix(FEC-7970): Change media from DRM to DRM is not working

---

karma.conf.js
src/dash-adapter.js

Event listener had a typo, and some other places, causing adaptation event to not be handled.

fix(FEC-8130): typo in adaptation event listener

---

src/dash-adapter.js

Send start time only if bigger then -1.

fix(FEC-8203): Live with DVR is not playing live edge in first play 

---

package.json
yarn.lock

updating shaka version to 2.3.3-k-3

chore: update shaka-player version 2.3.3-k-3

---

.eslintrc.json
.flowconfig
.prettierignore
.prettierrc
README.md
flow-typed/modules/playkit-js.js
flow-typed/modules/shaka-player.js
karma.conf.js
package.json
src/dash-adapter.js
src/drm/playready.js
src/drm/widevine.js
src/index.js
test/.eslintrc.json
test/setup/load-specs.js
test/src/dash-adapter.spec.js
test/src/drm/fake-drm-data.js
test/src/drm/playready.spec.js
test/src/drm/widevine.spec.js
webpack.config.js
yarn.lock

Add prettier settings for code style.

chore: prettier

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Use our own stream for VoD testing.
Fix async tests that don't have catch clauses:
```javascript
Promise.then().catch(e => {done(e))
try { ... } catch (e) { done(e); }
```
Fix failing audio tests following #58

tests: use kaltura VOD stream and fix tests

---

src/dash-adapter.js

Adding getCurrentQuality API for the quality watcher feature.
https://github.com/kaltura/playkit-js/pull/295

feat(FEC-7808): quality watcher for the player

---

.github/PULL_REQUEST_TEMPLATE.md

chore: fix typo in pull request template

---

package.json
src/dash-adapter.js
src/drm/playready.js
src/drm/widevine.js
test/src/dash-adapter.spec.js
test/src/drm/playready.spec.js
test/src/drm/widevine.spec.js
yarn.lock

Consider `drm.keySystem` config which specify the drm system to run with. 
Depends on https://github.com/kaltura/playkit-js/pull/330

feat(FEC-8700): add config option to specify DRM system

---

src/dash-adapter.js

Moved code from playkit-js to dash

feat(FEC-8975): QoS Data enhancment

---

package.json
src/dash-adapter.js
yarn.lock

Destroy and initialize shaka before and after ads for now(should be resolved by shaka later and it'll be replace by attach detach media)

feat(FEC-9227): support reInit of MSE

---

src/dash-adapter.js
src/drm/playready.js
src/drm/widevine.js
test/src/dash-adapter.spec.js
test/src/drm/playready.spec.js
test/src/drm/widevine.spec.js

shaka will select the correct adapter widevine or playready.

feat(FEC-9137): DRM protocol detection

---

package.json
src/dash-adapter.js
yarn.lock

Hanlde `condig.network.requestFilter` by shaka [`registerRequestFilter`](https://shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#registerRequestFilter) API
depends on https://github.com/kaltura/playkit-js/pull/391

feat(FEC-9271): expose interface and methods to enable customising DRM request/response

---

src/drm/widevine.js

fix logger to be in the right place for drm

fix: logs for drm checks

---

package.json
src/dash-adapter.js
yarn.lock

add check for MSE adapter to make sure we'll select the correct adapter for devices

fix(FEC-9342): Disable shaka on iOS

---

src/dash-adapter.js

fix(FEC-9512): save shaka lib on mediaSource adapter

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Support `requestFilter` returning promise

feat(FEC-9452): async request filter handlers

---

package.json
src/dash-adapter.js
test/src/dash-adapter.spec.js
yarn.lock

add `responseFilter` implementation
Depends on https://github.com/kaltura/playkit-js/pull/449
Solves FEC-9678

feat(FEC-9678): add response filter implementation to dash adapter

---

test/src/dash-adapter.spec.js

in ticket FEC-8975 functionallity was added to hls and dash to support kava but didn't have new unit tests to support it
solves FEC-9189

chore(FEC-9189): add tests for HLS and DASH adapters following FEC-8975

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

fix(FEC-10122): static _availableDrmProtocol doesn't get clear on reloading

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

If shaka config already has some drm configuration (for example from the app configuration) override the config defaults with it
solves FEC-10269

fix(FEC-10269): dash adapter overrides shaka DRM settings

---

.babelrc
package.json
src/dash-adapter.js
test/src/dash-adapter.spec.js
yarn.lock

upgrade shaka to current latest, note this is a major change with breaking changes(see below).
issue: getManifest was marked as API which could change any time.
solution: add an extra check to make sure it's not breaking our API, keeps the tests as is to help us to be aware of changes on this API.
Some tests are not valid anymore since the last version they changed internal function to private.
Solve: FEC-10356.

feat(FEC-10356): upgrade Shaka

---

package.json
test/src/dash-adapter.spec.js
yarn.lock

issue: version 3.0.x has an issue with some dash streams.
solution: downgrade to 2.5.13.

fix: downgrade shaka dependencies

---

src/dash-adapter.js

If shaka destroyed while loaded it throwing critical error.
Solution: save state which indicates were in destroy process and if this is error is thrown, change the error's severity to recoverable.

fix(FEC-10309): Player is triggering 7000 error when user navigation between pages quickly

---

package.json
yarn.lock

test: update shaka version

---

.babelrc

change modules value back to default.

build: change modules to default value

---

src/dash-adapter.js

Issue: stall skip 0 cause play/pause reject the play promise.
Solution: change to 0 after play promise fulfilled.

fix(FEC-10590): DOM play error on SmartTV on when stall happen on the beginning

---

src/dash-adapter.js

Issue: promises resolved on different timing and caused the main one to fulfilled
Solution: sync the destroy promise.

fix(FEC-10662): destroy promise doesn't fulfilled correctly

---

src/dash-adapter.js

Issue: text track doesn't have a config for styling, there is only an API for styling.
Solution: create a text container for the text track and add the options for styling the text track.

feat(FEC-10766): create text config section and option for styling

---

package.json
yarn.lock

Issue: memory leak from Shaka lib.
Solution: upgrade Shaka lib.

fix: update Shaka to fix the memory leak

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Issue: attachMediaSource start to load from the beginning instead of the last detach point.
Solution: start load from the last detach point.

fix(FEC-10773): reuse Shaka load option to start load from the detached point

---

package.json
yarn.lock

fix memory leak with webpack bundle process

fix(FEC-10995): update shaka to 3.0.8

---

src/dash-adapter.js

Support `withCredentials` on updated request.

feat(FEC-11091): add support for XMLHttpRequest.withCredentials in request filter

---

src/dash-adapter.js

Grab the actual DRM scheme from shaka.

fix(FEC-11140): DRM scheme might be incorrect in DRM_LICENSE_LOADED event

---

src/dash-adapter.js

feat(FEC-10817): expose the current time of the video element in live streams

---

src/dash-adapter.js

dont call `shaka.getManifest` where is not required
Solves FEC-11409

fix(FEC-11409): many shaka warnings printed in the log

---

package.json
yarn.lock

for DASH transition from dynamic to static

feat(FEC-11423): upgrade shaka to 3.0.13

---

src/dash-adapter.js

add polyfill for `window.Event` in IE11

fix(FEC-11429): something went wrong when start playing live dash on IE11 - regression

---

karma.conf.js
package.json
src/dash-adapter.js
test/src/dash-adapter.spec.js
yarn.lock

use the new structure of `TimedMetadata`
Solves FEC-11761
Depends on https://github.com/kaltura/playkit-js/pull/623

feat(FEC-11761): expose stream timed metadata - phase 2

---

src/dash-adapter.js

expose the drm info
releted pr: 
https://github.com/kaltura/kaltura-player-js/pull/515
https://github.com/kaltura/playkit-js/pull/624
https://github.com/kaltura/playkit-js-youbora/pull/82
solves: FEC-11785

fix(FEC-11785): [Web][Youbora] - update youbora options for drm system that is used by the player

---

package.json
yarn.lock

Related to https://github.com/kaltura/kaltura-player-js/pull/518
Solves FEC-11214

feat(FEC-11214): upgrade shaka to 3.3

---

.travis.yml
src/dash-adapter.js
test/src/dash-adapter.spec.js

solves: FEC-12189
related pr: 
https://github.com/kaltura/playkit-js/pull/652

fix(FEC-12189): Stream doesn't start if open a program with a bookmark

---

package.json
yarn.lock

Upgrade shaka-player to version 3.3.3
Related PR: https://github.com/kaltura/kaltura-player-js/pull/554
Resolves [FEC-12381](https://kaltura.atlassian.net/browse/FEC-12381)

chore(FEC-12381): upgrade shaka-player to version 3.3.3

---

.travis.yml

Add Travis webhook for MS Teams notifications

chore(FEC-12330): Need to add Travis CI build notifications to MS Teams 

---

package.json
src/dash-adapter.js
yarn.lock

Upgrade shaka player version and handle modified configuration api
Related PR: https://github.com/kaltura/kaltura-player-js/pull/561
Resolves FEC-12238

fix(FEC-12238): [WEB][ShakaPlayer] - upgrade shaka player to v4.1.2

---

package.json
yarn.lock

linked PR https://github.com/kaltura/kaltura-player-js/pull/569

feat(FEC-12491):upgrade shaka player v4.2.1

---

package.json
yarn.lock

fix(FEC-12779): upgrade shaka v4.3.0

---

package.json
yarn.lock

upgrade shaka player v4.3.3
FEC-12877

feat(FEC-12874): upgrade shaka player library to v4.3.3

---

package.json
src/dash-thumbnail-controller.js
test/src/dash-thumbnail-controller.spec.js
yarn.lock

fix(FEC-12988): fix image tracks row/cols values got mixed

---

package.json
yarn.lock

feat(FEC-13082): upgrade shaka player v4.3.5

---

test/src/dash-adapter.spec.js

fix(FEC-13102): playkit-js -dash - live Test failed

---

package.json
yarn.lock

feat(FEC-13213): upgrade shaka player v4.3.7

---

package.json
yarn.lock

solves FEC-13361
related pr: https://github.com/kaltura/kaltura-player-js/pull/650

fix(FEC-13363): Upgrade shaka latest

---

.github/workflows/run_canary.yaml

fix(FEC-133390): add canary workflow that uses script in common

---

.github/workflows/run_canary.yaml

fix(FEC-13390): use canary workflow from common master

---

package.json
yarn.lock

resolves: https://kaltura.atlassian.net/browse/FEC-13464

fix(FEC-13464): Upgrade shaka latest

---

package.json
yarn.lock

solves: https://kaltura.atlassian.net/browse/FEC-13522

fix(FEC-13522): upd shaka player

---

src/dash-adapter.js
src/default-config.json

feat(FEC-13574): Add support in stallDetectionThreshold min value is 2

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
webpack.config.js
yarn.lock

fix(FEC-13669): Aligning all repos with the latest kaltura-browserslist-config to eliminate different browser target among repos

---

src/assets/style.css
src/dash-adapter.ts

add `applyTextTrackStyles` method that allows apply custom styles to text-track
**Fix:**

feat(FEC-13664): add applyTextTrackStyles method

---

karma.conf.js
package.json
tests/src/dash-adapter.spec.js
yarn.lock

Upgrade shaka and fix test failures
Resolves FEC-14459

fix(FEC-14459): upgrade shaka version to 4.14.9
