karma.conf.js
src/dash-adapter.js
test/src/dash-adapter.spec.js

align with playkit-js caption refactor
need to hide native text tracks and use emulated display via HTML because not all browsers support all TextTrack API or VTTCue as defined by spec

feat: captions refactor

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

To support playkit default tracks flow we start shaka text tracks as inactive instead of take the active track from shaka (in case no track defined in the configuration of shaka it will be the first track in the manifest).

fix(FEC-7233): when parsing text tracks mark all as inactive

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

we listen to shaka `buffering` event and trigger `waiting/playing` accordingly.
sometimes the video element itself also triggers them and we get redundant events.
in this change we listen to the video element events, and only if them have not been triggered from the video tag we trigger the, from shaka

fix(FEC-7207): redundant buffering events

---

src/dash-adapter.js

Created an object to hold all the event handlers, so we can unbind it properly. 
Today we don't really unbind the handler because it's a new handler and not a reference to the previous one.

fix: clear event binding function references

---

src/dash-adapter.js

Updated the source type of the media according to the new types in playkit-js

fix: source type update

---

package.json
src/dash-adapter.js
src/text-displayer.js
yarn.lock

* upgrade shaka to 2.3.3 for https://github.com/google/shaka-player/issues/979 fix
* fix shaka v2.3.3 text tracks issue (hidden text tracks not handled see https://github.com/google/shaka-player/issues/1058) by custom text displayer

fix(FEC-7034): player gets stuck at the end after replay - ie11

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Removed the label in the video track as we set it in the VideoTrack.js in core

feat(FEC-7330): enable setting custom track labels by app

---

src/dash-adapter.js

The merge order for the config gave default config precedence over the application supplied config

fix(FEC-8396): media source adapters default config overrides the player supplied config

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

use shaka `setTextTrackVisibility` to set text track display mode according to `useNativeTextTrack` config flag.
This change is part of https://github.com/kaltura/playkit-js-hls/pull/65/ and https://github.com/kaltura/playkit-js/pull/263 - removing the overhead of handling in playkit-js is possible by using the Shaka APIs to set track visibility.

fix(FEC-7935): fix text selection logic

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

creating an audio track array of unique languages
no need to ID and setting the active, it is set by the player.
using getAudioLanguagesAndRoles() to get the list of languages from shaka.

fix(FEC-7590): filter Shaka audio tracks by language and not bitrate

---

karma.conf.js
src/dash-adapter.js
src/default-config.json

Use kaltura JSONP service to allow getting the redirected playManifest URL directly.
This is to avoid issues with UA that consider CORS 302 responses as unsecured(IE11)

feat(FEC-8553): add ability to force redirect kaltura playManifest urls

---

src/dash-adapter.js

shaka config drm is not updated. sent `config._shakaConfig` to the `setDrmPlayback()` function, instead of the `config` object.

fix(FEC-8666): cannot play dash drm

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Cannot assign `videoElement.currentTime` before `loadedmetadata` is fired.
Used the `_loadPromise` as a flag.

fix(FEC-8684): IE11 live dash playback is stuck

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Instead of waiting for shaka to load (which is done after load event) letting dash player wait for metadata loaded event.

fix(FEC-8711): live in IE has a small jump in the stream after a second

---

src/dash-adapter.js

Listening to network response to identify segment and manifest load and pass it to engine

FEC-8975 QoS data enhancement

---

src/dash-adapter.js

feat(FEC-8975): adding segment size in target buffer when exceeding maxmax

feat(FEC-8975): adding segment size in target buffer when exceeding maxmax

---

src/dash-adapter.js

Add support for replay after ads finish to return to beginning

fix(FEC-9262): playback doesn't return to start after playback with ads in LG TV

---

src/dash-adapter.js

occurred on DRM content only `LOAD_DATA` on SMART TV could take a moment and user can seek before - check if `SEEKED` event occurred before.
Couldn't resolve with `LOADED_METADATA` seek failed on earlier version of TV.

fix(FEC-9316): seek doesn't work before video finished loading

---

src/dash-adapter.js

Solve FEC-9316.
unlisten of loaded_data wasn't always earlier enough.
add check for seeked event occurred and don't seek on loaded_data event

fix: seek doesn't work before video finished loading

---

package.json
src/dash-adapter.js
yarn.lock

to use new licenseTime stats metric from Shaka upgraded Shaka to 2.5.9
listening to DRM_SESSION_UPDATE shaka event and triggering new DRM_LICENSE_RESPONSE playkit event with the license time
Solves FEC-9109

feat(FEC-9109): add DRM Load time metric

---

package.json
src/dash-adapter.js
src/drm/playready.js
src/drm/widevine.js
test/src/dash-adapter.spec.js
test/src/drm/fake-drm-data.js
test/src/drm/playready.spec.js
test/src/drm/widevine.spec.js
yarn.lock

removed redundant base DRM class in favour of typed interface, as part of FEC-10290 changes in https://github.com/kaltura/playkit-js/pull/446

 feat(FEC-10290): use IDrmProtocol for DRM handlers

---

package.json
src/dash-adapter.js
src/default-config.json
test/src/dash-adapter.spec.js
yarn.lock

Issue: encrypted liner channel sometimes constantly changes from buffering to playing
Solution: upgrade shaka - fixes for live and smartTV optimizations - added fixes for test and change the default bufferingGoal to 60s as we have for HLS.
remove `_getCurrentSegmentLength` which calculated from a recent segment that doesn't fit shaka calculation which used `getMaxSegmentDuration` instead.
Solve: FEC-10435.

feat(FEC-10435): upgrade shaka for fixing live issue and optimizations for smartTV

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Issue: adapter fire waiting and playing before it fired from the video element.
There is an incorrect situation when playing fired twice for DRM content and waiting fired before play.
Solution: use this mechanism only after first playing to make sure that buffering will be handled after first playing when buffering should change the buffering state.

fix(FEC-10840): incorrect waiting and playing event comes from dash adapter

---

CHANGELOG.md
package.json
src/dash-adapter.js
src/parser/adaptation-set.js
src/parser/dash-manifest-parser.js
src/parser/essential-property.js
src/parser/parser-utils.js
src/parser/representation.js
src/parser/segment-template.js
test/src/parser/dash-manifest-parser.spec.js
test/src/parser/manifests.js

Shaka player does not support parsing of image type adaptation set, so need to create our own dedicated parser for this.
We will register to the response filter and extract the image tracks data in the following raw structure:
- AdaptationSet
- ?EssentialProperty
- SegmentTemplate
- List<Representation>
- ?EssentialProperty
See diagram for better understanding of the flow:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/playkit-js-dash/131)

feat(FEC-10973): parse image tracks from dash manifest

---

package.json
src/dash-adapter.js
src/dash-thumbnail-controller.js
src/parser/dash-manifest-parser.js
src/parser/parser-utils.js
src/parser/segment-template.js
test/src/dash-adapter.spec.js
test/src/dash-thumbnail-controller.spec.js
test/src/parser/dash-manifest-parser.spec.js
test/src/parser/manifests.js
yarn.lock

* Add `DashThumbnailController` which controls and manage the image tracks.
* Add `getThumbnail(time: number): ?ThumbnailInfo` API implementation.
* Add parsing image tracks mechanism.
* Add `selectImageTrack` API implementation
* Add logic which optimise the manifest parsing on live manifests.

feat(FEC-10768): expose in-stream DASH thumbnails

---

src/dash-thumbnail-controller.js

feat(FEC-10941): Use In-Stream DASH thumbnails on the timeline

---

src/dash-adapter.js

Issue: stall detector doesn't get the change of stallSkip after it loaded and stallSkip 0.1 cause freezes on old SmartTV.
Solution: Handle it on playkit https://github.com/kaltura/playkit-js/pull/552

fix(FEC-11082): remove handling of DOM play error on SmartTV on when stall happen on the beginning

---

package.json
src/dash-adapter.js
yarn.lock

SMPTE-TT Subtitles fix
- updated shaka to 3.0.10
- moved useShakaTextTrackDisplay from playback.options.playback.options.html5.dash to text
- added useShakaTextTrackDisplay in _getParsedTextTracks when creating TextTrack and kind is an empty string
depends on https://github.com/kaltura/kaltura-player-js/pull/432
solves FEC-11126

fix(FEC-11126): upgrade shaka to 3.0.10

---

src/dash-adapter.js

Issue: Tizen 4 has stalled on the beginning of the media/after first seek we want to make sure the media wouldn't stop.
Solution: make a small seeks until playback keeps playing.

fix(FEC-11136): Tizen 4 got stuck on the beginning of the media

---

src/dash-adapter.js

Issue: Tizen 4 has stalled on the middle of the media, after seek we want to make sure the media wouldn't stop.
Solution: make a small seeks until playback keeps playing.

fix(FEC-11136): Tizen 4 got stuck on the middle of the media

---

src/dash-adapter.js

Issue: doesn't adaptive should select the first one if it's not in the range for capToPlayerSize and ABR restrictions.
Solution: always select the first one if it's not adaptive.

fix(FEC-11126): select the lowest value if we're not adaptive mode

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Issue: ABR auto-selection doesn't select the correct bandwidth.
Solution: Shaka parsing the variants with bandwidth for a variant which could be the bandwidth video itself or video+audio.
Select the videoBandwidth if it exists.

fix(FEC-11268): incorrect video bandwidth parsed

---

src/dash-adapter.js

Issue: applyRestriction doesn't trigger from playkit, no restriction has changed.
Solution: should apply the logic for capLevelToPlayerSize once tracks are available., it shouldn't change from playkit at all.

fix(FEC-11270): cap to player size doesn't apply

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

add `safeSeekOffset` to the dvr window calculation 
Solves FEC-11419

fix(FEC-11419): explore why Live Start over starts with few seconds delay

---

src/dash-adapter.js

**issue:**
once dash is triggering critical error event, we are not destroying the engine.
**solution:**
destroying engine when critical event is being fired.
Solves FEC-11492

fix(FEC-11492): dash adapter is not destroyed when network is offline

---

karma.conf.js
src/dash-adapter.js
test/src/dash-adapter.spec.js

shaka is increasing the `seekRange.start` between manifest loadings.
so ignore this update if it's start over.
Solves FEC-11473

fix(FEC-11473): start of dvr window is going back and forth while start over

---

src/dash-adapter.js

listen to shaka 'emsg' event
push the emsg detail as cue point to a metadata track for `TIMED_METADATA` to be fired in time
fired `TIMED_METADATA_ADDED` ith the cue point
Depends on https://github.com/kaltura/playkit-js/pull/618
Related to https://github.com/kaltura/kaltura-player-js/pull/509
Solves FEC-11632

feat(FEC-11632): expose stream timed metadata

---

src/dash-adapter.js

pass `streaming.lowLatencyMode` to shaka
Solves FEC-10548
Related to https://github.com/kaltura/playkit-js/pull/631

feat(FEC-10548): Low-Latency support

---

src/dash-adapter.js

add support for a specific webkit browser shaka says is not supported 
Solves FEC-11937

fix(FEC-11937): Player Compatible with Metrological Platform / Horizon4 Platform?

---

src/dash-adapter.js

currently, we remove shaka event binding on reset so we dont get shaka events after detach/attach

fix: do not remove shaka event bindings on reset but in destroy

---

src/dash-adapter.js
test/src/dash-adapter.spec.js

Make sure mediaKeys are removed before calling load, otherwise playing encrypted media can fail.
This can happen if reset was not called before load or if shaka failed to remove the mediaKeys on reset, which is something that can happen specifically when using the same video element for ads like with ima on smart tv.
Resolves FEC-12089

fix(FEC-12089): Tizen playback breaks after ad finishes

---

src/assets/style.css
src/dash-adapter.js

issue: the player uses the shaka UITextDisplayer plugin to render text tracks with our container but does not load all relevant CSS class
fix: update the CSS file and replace the container
solves: FEC-12479
related pr: https://github.com/kaltura/playkit-js/pull/660

fix(FEC-12479): [Dash] - Subtitles are too small and not centered

---

package.json
src/dash-adapter.js
test/src/dash-adapter.spec.js
yarn.lock

see https://github.com/kaltura/playkit-js/pull/633
solves: FEC-11697 and FEC-11893
related pr: 
https://github.com/kaltura/playkit-js-hls/pull/161
https://github.com/kaltura/playkit-js/pull/633

fix(FEC-11697): 2 captions are selected in the menu

---

src/assets/style.css

issue: on TV chome don't work in full-screen mode, so  the: fullscreen css doesn’t apply
fix:  add media query
solves: FEC-12539

fix(FEC-12539): Shaka text displayer font size too small on TVs

---

src/assets/style.css
src/dash-adapter.js

solves: FEC-12539 - Regression 
**issue:** the previous fix is incorrect since the media query refers to the screen size and not the player size
**fix:** The :fullscreen [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) is not applied in samrtTvs, so instead i relying on the Env.IsSmartTv env variable

fix(FEC-12539): Shaka text displayer font size too small on TVs - Regression

---

src/dash-adapter.js

Revert - TV font size bug fixes - regression
revert all prsrelated to this bug: https://github.com/kaltura/playkit-js-dash/pull/208   https://github.com/kaltura/playkit-js-dash/pull/210 https://github.com/kaltura/playkit-js-dash/pull/205
solves: FEC-12622

fix(FEC-12622): Revert - TV font size bug fixes - regression

---

src/dash-adapter.js
src/default-config.json

emsg metadata cues can take up a lot of memory because they contain binary data
this configuration allows toggling the emsg listener off if needed
resolves FEC-12615
related PR: https://github.com/kaltura/playkit-js/pull/668

fix(FEC-12615): add configuration to toggle emsg listener

---

src/dash-adapter.js

Shaka Text Track Displayer does not work unless  useNativeTextTrack set to true
solves: FEC-12691
related pr: 
https://github.com/kaltura/playkit-js/pull/671
https://github.com/kaltura/kaltura-player-js/pull/586

fix(FEC-12691): Shaka Text Track Displayer does not work unless useNativeTextTrack set to true

---

src/dash-adapter.js

See here [JSDoc: Class: shaka.extern](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Track)
the Track.primary filed in dash parsed track (return form shaka.getTextTracks() API) indicates the default track
Which ignored by the adapter 
(Unlike Hls Adapter which handles default track which indicated by Track.default field there)
solves FEC-12776

fix(FEC-12776): Dash Adapter does not support Default track from stream

---

src/dash-adapter.js

Support setting startTime 0.
Resolves [FEC-13108](https://kaltura.atlassian.net/browse/FEC-13108).
[FEC-13108]: https://kaltura.atlassian.net/browse/FEC-13108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13108): Start time can't be set to 0 in loadMedia for live with dvr

---

karma.conf.js
package.json
src/cache/asset-cache.ts
src/dash-adapter.ts
tests/src/cache/asset-cache.spec.js
tests/src/dash-adapter.spec.js
tests/src/utils/test-utils.js
yarn.lock

- Update shaka to version which has the new preload API + preload bug fixes
- Use shaka preload API and save the result (preloadManager instance) in a cache
- If we try to load a manifest url and it has been previously cached, shaka instance load() will accept the preloadManager instead of the manifest url. This results in a shortened load time.
preloadManager instances only work with the shaka player that they were created by, which required the following changes:
- Instead of having one instance of shaka per adapter we now have one shared instance per player (mapped by video element id)
- Destroying a shaka instance invalidates its preloadManagers and also renders it unusable (forcing creation of a new instance) so it can only be destroyed if it has no preloadManagers
- On destroy, if …

feat(FEC-13946): Player core - Use shaka preload mechanism during playlist playback 

---

package.json
src/dash-adapter.ts
webpack.config.js
yarn.lock

enhancement.
**Requirement:**
The requirement is to expose `kind` field for audio and text tracks according to accessibility parameters.
- audio tracks: possible values: `main`, `description` 
- text tracks: possible values: `subtitles`, `captions`
**Changes in this PR:**
for audio tracks:
- filter `sameLangAudioVariants` also by `role` field to distinguish between a11y audio stream and regular one
- check if the audio stream is accessible according to `accessibilityPurpose` field
- add `kind` field to `audioTracks` parsed in dash-adapter
for text tracks:
- `kind` field already exists on `textTracks` in dash-adapter
also fix the playkit-js dep in webpack file.
**depends on** [PR](https://github.com/kaltura/playkit-js/pull/815)

feat(FEC-14419): Expose Accessibility Audio \ Text Track Indications
